version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./app:/var/www  # Volumen persistente para la app
    networks:
      - laravel_network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    ports:
      - "8000:9000"

  db:
    image: mysql:8.0
    container_name: laravel_db
    networks:
      - laravel_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql  # Volumen persistente para la base de datos

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - laravel_network


  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - ./app:/var/www  # Volumen persistente para la app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - laravel_network
    depends_on:
      - app

networks:
  laravel_network:
    driver: bridge